WebApplicationTireFitting/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationTireFitting.Models;

namespace WebApplicationTireFitting.Controllers
{
    public class CarsController : Controller
    {
        private readonly DB_Kursova_Tire_FittingContext _context;
        IWebHostEnvironment _appEnvironment;

        public CarsController(DB_Kursova_Tire_FittingContext context, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            var dB_Kursova_Tire_FittingContext = _context.Cars.Include(c => c.IdClientNavigation).Include(c => c.IdTypeOfCarNavigation);
            return View(await dB_Kursova_Tire_FittingContext.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.IdClientNavigation)
                .Include(c => c.IdTypeOfCarNavigation)
                .FirstOrDefaultAsync(m => m.IdCar == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            ViewData["IdClient"] = new SelectList(_context.Clients, "IdClient", "FullName");
            ViewData["IdTypeOfCar"] = new SelectList(_context.TypeOfCars, "IdTypeOfCar", "TypeOfCar1");
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCar,Name,Owner,IdClient,IdTypeOfCar,PathCarImg")] Car car, IFormFile uploadedFile)
        {
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();

                //збереження зображення
                // путь к папке Files
                string path = $"/Files/CarImg/{car.IdCar}_{uploadedFile.FileName}";
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

                car.PathCarImg = path;
                await _context.SaveChangesAsync();
                //
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdClient"] = new SelectList(_context.Clients, "IdClient", "FullName", car.IdClient);
            ViewData["IdTypeOfCar"] = new SelectList(_context.TypeOfCars, "IdTypeOfCar", "TypeOfCar1", car.IdTypeOfCar);
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            ViewData["IdClient"] = new SelectList(_context.Clients, "IdClient", "FullName", car.IdClient);
            ViewData["IdTypeOfCar"] = new SelectList(_context.TypeOfCars, "IdTypeOfCar", "TypeOfCar1", car.IdTypeOfCar);
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCar,Name,Owner,IdClient,IdTypeOfCar,PathCarImg")] Car car, IFormFile uploadedFile)
        {
            if (id != car.IdCar)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //
                    //якщо було вибрано файл то він замінює попередній
                    if (uploadedFile != null)
                    {
                        //збереження зображення
                        // путь к папке Files

                        string path = $"/Files/CarImg/{car.IdCar}_{uploadedFile.FileName}";
                        // сохраняем файл в папку Files в каталоге wwwroot
                        using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                        {
                            await uploadedFile.CopyToAsync(fileStream);
                        }

                        FileInfo fileInf = new FileInfo(_appEnvironment.WebRootPath + car.PathCarImg);
                        if (fileInf.Exists)
                        {
                            fileInf.Delete();
                        }

                        car.PathCarImg = path;
                    }
                    //

                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.IdCar))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdClient"] = new SelectList(_context.Clients, "IdClient", "FullName", car.IdClient);
            ViewData["IdTypeOfCar"] = new SelectList(_context.TypeOfCars, "IdTypeOfCar", "TypeOfCar1", car.IdTypeOfCar);
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.IdClientNavigation)
                .Include(c => c.IdTypeOfCarNavigation)
                .FirstOrDefaultAsync(m => m.IdCar == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Cars.FindAsync(id);
            //видаляє зображення
            FileInfo fileInf = new FileInfo(_appEnvironment.WebRootPath + car.PathCarImg);
            if (fileInf.Exists)
            {
                fileInf.Delete();
            }
            //
            _context.Cars.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Cars.Any(e => e.IdCar == id);
        }
    }
}

//git testttt

WebApplicationTireFitting/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationTireFitting.Models;

namespace WebApplicationTireFitting.Controllers
{
    public class OrdersController : Controller
    {
        private readonly DB_Kursova_Tire_FittingContext _context;

        public OrdersController(DB_Kursova_Tire_FittingContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var dB_Kursova_Tire_FittingContext = _context.Orders.Include(o => o.IdCarNavigation).Include(o => o.IdClientNavigation);
            return View(await dB_Kursova_Tire_FittingContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.IdCarNavigation)
                .Include(o => o.IdClientNavigation)
                .FirstOrDefaultAsync(m => m.IdOrder == id);
            //
                // передача на сторінку масива з Services
            ViewData["Materials"] = await _context.Orders
                .Where(p => p.IdOrder == id)
                .Include(v => v.MaterialsOrders)
                .ThenInclude(p => p.IdMaterialsNavigation)
                .ToListAsync();

            ViewData["Workers"] = await _context.Orders
                .Where(p => p.IdOrder == id)
                .Include(v => v.OrderWorkers)
                .ThenInclude(p => p.IdWorkerNavigation)
                .ToListAsync();

            ViewData["Services"] = await _context.Orders
                .Where(p => p.IdOrder == id)
                .Include(v => v.ServiceOrders)
                .ThenInclude(p => p.IdServiceNavigation)
                .ToListAsync();
            //
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            //
            ViewData["Materials"] = _context.Materials.ToList();
            ViewData["Workers"] = _context.Workers.ToList();
            ViewData["Services"] = _context.Services.ToList();
            //
            ViewData["IdCar"] = new SelectList(_context.Cars, "IdCar", "Name");
            ViewData["IdClient"] = new SelectList(_context.Clients, "IdClient", "FullName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdOrder,Date,IdClient,IdCar,Price")] Order order, int[] idMaterials, int[] idWorkers, int[] idServices)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                //
                foreach (var n in idMaterials)
                {
                    order.MaterialsOrders.Add(new MaterialsOrder
                    {
                        IdOrderNavigation = order,
                        IdMaterialsNavigation = _context.Materials.FirstOrDefault(p => p.IdMaterials == n)
                    });
                }

                foreach (var n in idWorkers)
                {
                    order.OrderWorkers.Add(new OrderWorker
                    {
                        IdOrderNavigation = order,
                        IdWorkerNavigation = _context.Workers.FirstOrDefault(p => p.IdWorker == n)
                    });
                }

                foreach (var n in idServices)
                {
                    order.ServiceOrders.Add(new ServiceOrder
                    {
                        IdOrderNavigation = order,
                        IdServiceNavigation = _context.Services.FirstOrDefault(p => p.IdService == n)
                    });
                }
                //
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //
            //
            ViewData["Materials"] = _context.Materials.ToList();
            ViewData["Workers"] = _context.Workers.ToList();
            ViewData["Services"] = _context.Services.ToList();
            //
            //
            ViewData["IdCar"] = new SelectList(_context.Cars, "IdCar", "Name", order.IdCar);
            ViewData["IdClient"] = new SelectList(_context.Clients, "IdClient", "FullName", order.IdClient);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);

            //
            // передача на сторінку масива з Services
            //
            ViewData["MaterialsFull"] = _context.Materials.ToList();
            ViewData["WorkersFull"] = _context.Workers.ToList();
            ViewData["ServicesFull"] = _context.Services.ToList();
            //
            ViewData["Materials"] = await _context.Orders
                .Where(p => p.IdOrder == id)
                .Include(v => v.MaterialsOrders)
                .ThenInclude(p => p.IdMaterialsNavigation)
                .ToListAsync();

            ViewData["Workers"] = await _context.Orders
                .Where(p => p.IdOrder == id)
                .Include(v => v.OrderWorkers)
                .ThenInclude(p => p.IdWorkerNavigation)
                .ToListAsync();

            ViewData["Services"] = await _context.Orders
                .Where(p => p.IdOrder == id)
                .Include(v => v.ServiceOrders)
                .ThenInclude(p => p.IdServiceNavigation)
                .ToListAsync();
            //

            if (order == null)
            {
                return NotFound();
            }
            ViewData["IdCar"] = new SelectList(_context.Cars, "IdCar", "Name", order.IdCar);
            ViewData["IdClient"] = new SelectList(_context.Clients, "IdClient", "FullName", order.IdClient);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdOrder,Date,IdClient,IdCar,Price")] Order order, int[] idMaterials, int[] idWorkers, int[] idServices)
        {
            if (id != order.IdOrder)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {


                    _context.Update(order);
                    //
                    var OrderWorkers = _context.OrderWorkers
                        .Where(p => p.IdOrder == id)
                        .ToListAsync();
                    foreach (var item in await OrderWorkers)
                    {
                        _context.OrderWorkers.RemoveRange(item);
                    }

                    var MaterialsOrders = _context.MaterialsOrders
                        .Where(p => p.IdOrder == id)
                        .ToListAsync();
                    foreach (var item in await MaterialsOrders)
                    {
                        _context.MaterialsOrders.RemoveRange(item);
                    }

                    var ServiceOrders = _context.ServiceOrders
                        .Where(p => p.IdOrder == id)
                        .ToListAsync();
                    foreach (var item in await ServiceOrders)
                    {
                        _context.ServiceOrders.RemoveRange(item);
                    }

                    //
                    foreach (var n in idMaterials)
                    {
                        order.MaterialsOrders.Add(new MaterialsOrder
                        {
                            IdOrderNavigation = order,
                            IdMaterialsNavigation = _context.Materials.FirstOrDefault(p => p.IdMaterials == n)
                        });
                    }

                    foreach (var n in idWorkers)
                    {
                        order.OrderWorkers.Add(new OrderWorker
                        {
                            IdOrderNavigation = order,
                            IdWorkerNavigation = _context.Workers.FirstOrDefault(p => p.IdWorker == n)
                        });
                    }

                    foreach (var n in idServices)
                    {
                        order.ServiceOrders.Add(new ServiceOrder
                        {
                            IdOrderNavigation = order,
                            IdServiceNavigation = _context.Services.FirstOrDefault(p => p.IdService == n)
                        });
                    }
                    //

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.IdOrder))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCar"] = new SelectList(_context.Cars, "IdCar", "Name", order.IdCar);

WebApplicationTireFitting/Views/Shared - Копировать/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationTireFitting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @* kendo *@
    <link href="https://kendo.cdn.telerik.com/2021.1.119/styles/kendo.bootstrap-v4.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2021.1.119/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.1.119/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.1.119/js/kendo.aspnetmvc.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.3.913/js/pako_deflate.min.js"></script>
    @* kendo *@
    @* для експорту зображень *@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js"
            integrity="sha256-c9vxcXyAG4paArQG3xk6DjyW/9aHxai2ef9RpMWO44A=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
    @* для експорту зображень *@
    @* для роботи графіків*@
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
    @* для роботи графіків*@

    <script src="~/js/maskinput.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationTireFitting</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Машини</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Клієнти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Materials" asp-action="Index">Матеріали</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Замовлення</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Index">Посада</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Сервіс</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TypeOfCars" asp-action="Index">Типи машин</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workers" asp-action="Index">Працівники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Звіти</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplicationTireFitting - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>